runtime: python37

handlers:
- url: /static/
  static_dir: static
- url: /media/
  static_dir: media
- url: /oauth2callback
  script: auto
- url: /.*
  script: auto
  secure: always
- url: /admin/.*
  script: auto
  login: admin
  secure: always
- url: /login/.*
  script: auto
  login: required
  secure: always
  redirect_http_response_code: 301
